### ISSUE TITLE
Deprecated 

### ISSUE THREAD

**Issue by ucyo** [climate-v/nc2zarr-webapp#5]
https://github.com/climate-v/nc2zarr-webapp/blob/fcb9c2b134340d6e8cd1e095ce1287b32fe63697/docker-compose.override.yaml#L20

Geting following warning

```shell
> docker compose ps
WARN[0000] `scale` is deprecated. Use the `deploy.replicas` element
```
We should not be using deprecated code

**Comment by b-pos465** [comment]
Thanks, I fixed it!

**Comment by ucyo** [comment]
As in issue #4 please refer to a commit if this is being fixed
